SVN_REVISION.blurb=Subversion revision number that''s currently checked out to the workspace, such as "12345". Not set when multiple module locations are used.
SVN_URL.blurb=Subversion URL that''s currently checked out to the workspace. Not set when multiple module locations are used.
SVN_REVISION_1.blurb=Same as SVN_REVISION but for the 1st location (SVN_REVISION_2, 3, 4... might be available if you add more locations to the job).
SVN_URL_1.blurb=Same as SVN_URL but for the 1st location (SVN_URL_2, 3, 4... might be available if you add more locations to the job).
SVN_REVISION_MAX.blurb=Maximum revision number of all locations in the job/build.
SVN_URL_MAX.blurb=URL of the location with SVN_REVISION_MAX.